export const LOG_REDACTION_PATHS = [
  'authorization',
  'Authorization',
  'password',
  'secret',
  'token',
  'accessToken',
  'apiKey',
  'clientSecret',
  'UPSTOX_ACCESS_TOKEN',
  'UPSTOX_CLIENT_SECRET',
  'GNEWS_API_KEY',
  'OPENROUTER_API_KEY',
  'META_WHATSAPP_ACCESS_TOKEN',
  'META_WHATSAPP_APP_SECRET',
  'META_WHATSAPP_VERIFY_TOKEN',
  'DB_PASSWORD',
  'DATABASE_PASSWORD',
  'headers.authorization',
  'headers.Authorization',
  'req.headers.authorization',
  'req.headers.Authorization',
  'request.headers.authorization',
  'request.headers.Authorization',
  'body.accessToken',
  'body.apiKey',
  'body.clientSecret',
  'body.password',
  'body.secret',
  'body.token',
  'metadata.accessToken',
  'metadata.apiKey',
  'metadata.clientSecret',
  'metadata.password',
  'metadata.secret',
  'metadata.token',
  '*.authorization',
  '*.Authorization',
  '*.password',
  '*.secret',
  '*.token',
  '*.accessToken',
  '*.apiKey',
  '*.clientSecret',
  '*.*.authorization',
  '*.*.Authorization',
  '*.*.password',
  '*.*.secret',
  '*.*.token',
  '*.*.accessToken',
  '*.*.apiKey',
  '*.*.clientSecret',
] as const;

export const LOG_REDACTION_CENSOR = '[REDACTED]';

export const REQUEST_ID_HEADER = 'x-request-id';
