import * as Joi from 'joi';

export const environmentValidationSchema = Joi.object({
  MARKET_DATA_PROVIDER: Joi.string().valid('fixture', 'upstox').default('fixture'),
  MARKET_DATA_UNIVERSE: Joi.string().pattern(/^[A-Z0-9_-]{1,32}$/).default('DEVELOPMENT'),
  UPSTOX_CLIENT_ID: Joi.string().allow('').default(''),
  UPSTOX_CLIENT_SECRET: Joi.string().allow('').default(''),
  UPSTOX_REDIRECT_URI: Joi.string().uri().allow('').default(''),
  UPSTOX_ACCESS_TOKEN: Joi.string().allow('').default(''),
  UPSTOX_API_BASE_URL: Joi.string().uri({ scheme: ['https'] }).default('https://api.upstox.com'),
  UPSTOX_INSTRUMENT_FILE_URL: Joi.string().uri({ scheme: ['https'] })
    .default('https://assets.upstox.com/market-quote/instruments/exchange/NSE.json.gz'),
  UPSTOX_HTTP_TIMEOUT_MS: Joi.number().integer().min(1000).max(60000).default(10000),
  UPSTOX_MAX_RETRIES: Joi.number().integer().min(0).max(5).default(2),
  UPSTOX_RETRY_BASE_DELAY_MS: Joi.number().integer().min(100).max(10000).default(500),
  NEWS_PROVIDER: Joi.string().valid('', 'gnews').default(''),
  GNEWS_API_KEY: Joi.string().allow('').default(''),
  GNEWS_BASE_URL: Joi.string().uri({ scheme: ['https'] }).default('https://gnews.io/api/v4'),
  GNEWS_DEFAULT_LANGUAGE: Joi.string().lowercase().length(2).default('en'),
  GNEWS_DEFAULT_COUNTRY: Joi.string().lowercase().length(2).default('in'),
  GNEWS_MAX_RESULTS: Joi.number().integer().min(1).max(100).default(10),
  GNEWS_HTTP_TIMEOUT_MS: Joi.number().integer().min(1000).max(60000).default(10000),
  GNEWS_MAX_RETRIES: Joi.number().integer().min(0).max(5).default(2),
  GNEWS_RETRY_BASE_DELAY_MS: Joi.number().integer().min(100).max(10000).default(500),
  GNEWS_CACHE_TTL_MS: Joi.number().integer().min(0).max(3600000).default(300000),
  AI_PROVIDER: Joi.string().valid('', 'openrouter').default(''),
  OPENROUTER_API_KEY: Joi.string().allow('').default(''),
  OPENROUTER_BASE_URL: Joi.string().uri({ scheme: ['https'] })
    .default('https://openrouter.ai/api/v1'),
  OPENROUTER_MODEL: Joi.string().trim().min(1).default('openrouter/free'),
  OPENROUTER_HTTP_TIMEOUT_MS: Joi.number().integer().min(1000).max(120000).default(30000),
  OPENROUTER_APP_NAME: Joi.string().trim().min(1).max(100).default('swing-trading-assistant'),
  OPENROUTER_SITE_URL: Joi.string().uri({ scheme: ['http', 'https'] }).allow('').default(''),
  OPENROUTER_MAX_RETRIES: Joi.number().integer().min(0).max(3).default(2),
  OPENROUTER_RETRY_BASE_DELAY_MS: Joi.number().integer().min(100).max(10000).default(1000),
  OPENROUTER_CACHE_TTL_MS: Joi.number().integer().min(0).max(3600000).default(900000),
  MESSAGING_PROVIDER: Joi.string().valid('', 'meta-whatsapp').default(''),
  META_WHATSAPP_ACCESS_TOKEN: Joi.string().allow('').default(''),
  META_WHATSAPP_PHONE_NUMBER_ID: Joi.string().pattern(/^\d+$/).allow('').default(''),
  META_WHATSAPP_BUSINESS_ACCOUNT_ID: Joi.string().pattern(/^\d+$/).allow('').default(''),
  META_WHATSAPP_VERIFY_TOKEN: Joi.string().allow('').default(''),
  META_WHATSAPP_APP_SECRET: Joi.string().allow('').default(''),
  META_WHATSAPP_GRAPH_API_VERSION: Joi.string().pattern(/^v\d+\.\d+$/).default('v26.0'),
  META_WHATSAPP_BASE_URL: Joi.string().uri({ scheme: ['https'] })
    .default('https://graph.facebook.com'),
  META_WHATSAPP_HTTP_TIMEOUT_MS: Joi.number().integer().min(1000).max(60000).default(10000),
  META_WHATSAPP_ALLOWED_SENDER: Joi.string().allow('').default(''),
  META_WHATSAPP_TEMPLATE_LANGUAGE: Joi.string().pattern(/^[a-z]{2}(?:_[A-Z]{2})?$/).default('en_US'),
  META_WHATSAPP_MAX_RETRIES: Joi.number().integer().min(0).max(3).default(2),
  META_WHATSAPP_RETRY_BASE_DELAY_MS: Joi.number().integer().min(100).max(10000).default(500),
  META_WHATSAPP_DEDUP_TTL_SECONDS: Joi.number().integer().min(60).max(2592000).default(604800),
  NODE_ENV: Joi.string()
    .valid('development', 'test', 'production')
    .default('development'),
  APP_PORT: Joi.number().port().default(3000),
  DATABASE_HOST: Joi.string().trim().required(),
  DATABASE_PORT: Joi.number().port().default(5432),
  DATABASE_NAME: Joi.string().trim().required(),
  DATABASE_USER: Joi.string().trim().required(),
  DATABASE_PASSWORD: Joi.string().min(1).required(),
  REDIS_HOST: Joi.string().trim().required(),
  REDIS_PORT: Joi.number().port().default(6379),
  LOG_LEVEL: Joi.string()
    .valid('fatal', 'error', 'warn', 'log', 'debug', 'verbose')
    .default('log'),
});
