export enum EscalationReason {
  HIGH_EVENT_RISK = 'HIGH_EVENT_RISK',
  HIGH_UNCERTAINTY = 'HIGH_UNCERTAINTY',
  LOW_MODEL_CONFIDENCE = 'LOW_MODEL_CONFIDENCE',
  CONTRADICTORY_EVIDENCE = 'CONTRADICTORY_EVIDENCE',
  MISSING_CRITICAL_EVIDENCE = 'MISSING_CRITICAL_EVIDENCE',
  MODEL_REQUESTED_ESCALATION = 'MODEL_REQUESTED_ESCALATION',
  TOP_RANKED_CANDIDATE = 'TOP_RANKED_CANDIDATE',
}
