import { MarketRegime } from '../../market-regime/models/market-regime.enum';
import { CommonStrategyConfig } from '../shared/strategy-config';
import { ScoreBand } from '../shared/scoring';

export const TREND_PULLBACK_V1_CONFIG = {
  version: 'trend-pullback-v1',
  enabled: true,
  minimumHistory: 200,
  qualificationThreshold: '68',
  liquidityPeriod: 20,
  minimumAverageTradedValue: '50000000',
  blockedRegimes: [MarketRegime.RISK_OFF],
  regimeScores: { BULLISH: '100', NEUTRAL: '70', BEARISH: '20', RISK_OFF: '0' },
  missingSectorScore: '50',
  relativeStrengthRange: ['-5', '10'],
  rsiBand: ['30', '45', '60', '78'],
  roc20Range: ['-10', '3'],
  roc50Range: ['-5', '12'],
  normalizedAtrBand: ['0.4', '1', '3', '6'],
  recentHighPeriod: 20,
  swingLowPeriod: 5,
  minimumDepthPercent: '1',
  maximumDepthPercent: '15',
  depthBand: ['1', '3', '7', '15'] as ScoreBand,
  supportDistanceAtrRange: ['0.3', '2.5'] as const,
  contractionPeriod: 3,
  priorVolumePeriod: 20,
  contractionRatioRange: ['0.5', '1.2'] as const,
  recoveryPercentRange: ['0', '1'] as const,
  recoveryVolumeRange: ['0.8', '1.5'] as const,
  weights: {
    primaryTrendQuality: '15',
    pullbackDepth: '15',
    supportZoneQuality: '15',
    relativeStrength: '15',
    volumeContraction: '10',
    renewedBuyingStrength: '10',
    momentumHealth: '5',
    volatilityQuality: '5',
    marketRegimeFit: '5',
    sectorStrength: '5',
  },
} as const satisfies CommonStrategyConfig & Record<string, unknown>;
