export enum TradeEventType {
  CANDIDATE_CREATED = 'CANDIDATE_CREATED',
  CANDIDATE_SKIPPED = 'CANDIDATE_SKIPPED',
  TRADE_OPENED = 'TRADE_OPENED',
  STOP_CHANGED = 'STOP_CHANGED',
  TRADE_CLOSED = 'TRADE_CLOSED',
  USER_NOTE = 'USER_NOTE',
}
